runtime: python
runtime_config:
  operating_system: ubuntu22
  runtime_version: 3.10.0
entrypoint: streamlit run --server.port=8080 --server.address=0.0.0.0 --server.enableCORS=false --server.enableWebsocketCompression=false --server.enableXsrfProtection=false --server.headless=true vestavind.py
env: flex
network:
  session_affinity: true
manual_scaling:
  instances: 1