name: get_data
on:
  schedule:
    - cron: "* * * * *"

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run data fetch
        # For example, using `pytest`
        run: uv run python utils.py
        env: # Set the secret as an input
              AIVEN_USER: ${{ secrets.AIVEN_USER }}
              AIVEN_PASSWORD: ${{ secrets.AIVEN_PASSWORD }}
              AIVEN_HOST: ${{ secrets.AIVEN_HOST }}
              METNO_CLIENT_ID: ${{ secrets.METNO_CLIENT_ID }}
              METNO_CLIENT_SECRET: ${{ secrets.METNO_CLIENT_SECRET }}
              WUDERMAP_API_KEY: ${{ secrets.WUDERMAP_API_KEY }}
              HOLFUY_SECRET: ${{ secrets.HOLFUY_SECRET }}
              NVE_API_KEY: ${{ secrets.NVE_API_KEY }}
              ECOWITT_APPLICATIONKEY: ${{ secrets.ECOWITT_APPLICATIONKEY }}
              ECOWITT_APIKEY: ${{ secrets.ECOWITT_APIKEY }}
              ECOWITT_IMEI_STATION: ${{ secrets.ECOWITT_IMEI_STATION }}